feat(react-native): ability to switch between spotlight and grid mode
GetStream/stream-video-js pull request #756
Opened 2023-07-05 14:44 UTC by khushal87

2023-07-05 17:27 UTC, vanGalilea approved these changes

2023-07-05 20:41 UTC, santhoshvai commented on sample-apps/react-native/dogfood/src/components/ParticipantLayoutButton.tsx
> +import { CallParticipantsViewProps } from '@stream-io/video-react-native-sdk';
no need to export props from SDK for this

The integrators can do `React.ComponentProps<CallParticipantsView>["mode"]`

this is the reason why prop types are not exported in react-native for example..

2023-07-05 20:43 UTC, santhoshvai commented on sample-apps/react-native/dogfood/src/components/ParticipantLayoutButton.tsx
> +export type Mode = NonNullable<CallParticipantsViewProps['mode']>;
no need to export the type Mode also..

again in any screen  ` Mode = React.ComponentProps<CallParticipantsView>["mode"] can be used`

2023-07-05 20:45 UTC, santhoshvai commented on packages/react-native-sdk/src/components/CallParticipantsView.tsx
> +export type CallParticipantsViewProps = {
lets avoid exporting props unless absolutely necessary.. explained below

2023-07-05 20:45 UTC, santhoshvai requested changes
requesting to not export props

2023-07-05 20:46 UTC, santhoshvai commented on packages/react-native-sdk/src/components/CallParticipantsBadge.tsx
> -    top: -theme.spacing.sm,
nice removal.. negative margins are ugly unless

2023-07-06 09:39 UTC, santhoshvai approved these changes
Discussed props exporting.. and we preferrred that exporting is better as most people do not know React.ComponentProps yet

so lets keep as is!

2023-07-06 09:45 UTC, khushal87 commented
> Discussed props exporting.. and we preferrred that exporting is better as most people do not know React.ComponentProps yet
> 
> so lets keep as is!

Yes, it's about knowing, that's one thing. Plus I don't see any harm if we export it. We are doing the same thing just in a different way.

2023-07-06 10:29 UTC, merged